nav:
  Author: /author/
  Talks: /talks/

custom:
  license: CC BY-SA
  twitter_handle: 
  favicon: 
    # eg. generate with http://realfavicongenerator.net/
    desktop:
      url: /images/favicon.ico
    android:
      url: /images/favicon-192x192.png
    social_links:
      github: 
      twitter: 
      linkedin: 

social:
  twitter:
  github: 
  linkedin:   

projects:
  project:
    url: 
    description: 
  bechdel-project:
    url: 
    description: 